name: Exploring Concurrency

on: workflow_dispatch

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    concurrency:
      group: production-deploy 
    steps:
      - name: Deploy
        run: |
          sleep 30
          echo Deployed to Production
          
 

