name: Exploring environment variables

on: push
env:
  LEVEL: workflow

jobs:
  step_level_env_variables:
    env:
       LEVEL: job
    runs-on: ubuntu-latest
    steps:
      - name: Setup and read env variables on step level
        env:
          LEVEL: steps
        run: echo $LEVEL
      - name: Read job level environment variable
        run: echo $LEVEL
      - name: Read workflow level environment variable
        run: echo $LEVEL
